apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-api
  name: hello-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-api
    spec:
      containers:
      - image: mikewilliamson/hello-api
        name: hello-api
        resources: {}
status: {}
