apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-api
  name: hello-api
spec:
  ports:
  - name: 3000-3000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: hello-api
  type: LoadBalancer
status:
  loadBalancer: {}
